In [43]:
import pandas as pd
import numpy as np

In [3]:
car=pd.read_csv("quikr_car.csv")

In [4]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [5]:
car.shape

(892, 6)

In [6]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

## Data Cleaning
- year has many non-year numbers
- year object to int
- --
- price has ask for price
- price object to int
- --
- kms_driven has kms with integers
- kms_driven object top int
- --
- fuel_type has NaN values
- --
- keep first three words only from the name column

In [7]:
 backup=car.copy()

In [8]:
car=car[car['year'].str.isnumeric()]

In [9]:
car['year']=car['year'].astype(int)

In [10]:
car=car[car['Price']!="Ask for Price"]

In [11]:
car['Price'] = car['Price'].str.replace(',', '', regex=True)
car['Price'] = pd.to_numeric(car['Price'], errors='coerce')

In [12]:
car = car.dropna(subset=['Price']).astype({'Price': int})

In [13]:
car['kms_driven']=car['kms_driven'].str.split(' ').str.get(0).str.replace(',','', regex=True)

In [14]:
car=car[car['kms_driven'].str.isnumeric()]

In [15]:
car['kms_driven']=car['kms_driven'].astype(int)

In [16]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32
 3   Price       817 non-null    int32
 4   kms_driven  817 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 35.1+ KB

In [17]:
car=car[~car['fuel_type'].isna()]

In [18]:
car['name']=car['name'].str.split(' ').str.slice(0,3).str.join(' ') #3 is excluded means index 0 to 2

In [19]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [20]:
car=car.reset_index(drop=True) ## to reset the index and drop the previous index and

In [21]:
car.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [22]:
car[car['Price']>6e6]

                   name   company  year    Price  kms_driven fuel_type
534  Mahindra XUV500 W6  Mahindra  2014  8500003       45000    Diesel

In [23]:
car=car[car['Price']<6e6].reset_index(drop=True)

In [24]:
car.describe()

              year         Price     kms_driven
count   815.000000  8.150000e+02     815.000000
mean   2012.442945  4.017933e+05   46277.096933
std       4.005079  3.815888e+05   34318.459638
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.900000e+05   56879.000000
max    2019.000000  3.100000e+06  400000.000000

In [25]:
car.to_csv("Cleaned_Car_Data.csv")

# Model

In [26]:
x=car.drop(columns='Price')
y=car["Price"]

In [27]:
x

                       name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811          Tata Indica V2      Tata  2009       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813            Tata Zest XM      Tata  2018       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]

In [28]:
y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int32

In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [31]:
ohe = OneHotEncoder()
ohe.fit(x[['name','company','fuel_type']])

OneHotEncoder()

In [32]:
ohe.categories

'auto'

In [33]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),
                                    remainder='passthrough')

In [34]:
lr=LinearRegression()

In [35]:
pipe=make_pipeline(column_trans,lr)

In [36]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [37]:
y_preds=pipe.predict(x_test)

In [38]:
y_preds

array([ 700473.71088912,  174552.88229632,  310699.51031405,
        420664.61518758,  191857.12346129,  267694.99375705,
        763877.02223606,  326204.07656768,   98523.78857961,
        450038.97911401,  294056.3427325 ,  357106.48787829,
        407568.96547768,  341216.50953761,  443036.96155301,
        513788.56763143,  155189.45477136,  292110.22468299,
        301108.89526623, 2055345.65901516,  206954.07153046,
        353393.29925121,  506847.04856446,   25075.84707669,
        496439.69269948,  416576.03471641,  211371.54524819,
        273984.55580882,  193300.0096727 ,  157597.14581859,
        368299.0674566 ,  530671.84211416,  560835.8481921 ,
        287556.14501336,  238806.44502628,  315373.82225358,
        781704.36478385,  422701.48365212,  426465.36762153,
        309089.56064149,  486947.82921662,  678545.58721321,
        477042.78071474,  242641.08509465,  567931.04600094,
        294771.95300981,  354889.63971409,  388389.50693562,
        190659.34752978, 2055454.08948348,  526583.19912933,
       1564320.87886319,  420486.82768545,  239217.93105333,
        331763.31212503,  202833.71373412,  456109.86617871,
        301429.61457858,  294599.13765292,  340490.07352058,
        414243.50462702,  651623.00213371,  202842.43064408,
         64333.15883101,  356902.59594089,  488577.26985113,
        289516.57124704,   -4556.36612479,  361113.60688539,
        470571.46645257,  431057.54962131,  261411.65697456,
        578934.71093886,   59300.19178785,  145145.29505438,
        625813.6182294 ,  320152.52797312,  299477.86614874,
        297010.51808131,  578488.77059487,  185237.43966986,
        303403.64372891,  199684.91014148,  336995.3202448 ,
        409368.91125186,  230315.66921003,  600667.9884379 ,
        208183.46369549,  424493.74096618,  453285.97038127,
        304329.86891373,  355956.05173398,  284384.0640695 ,
        234833.44706246,  -27827.93267794,  226349.20828661,
        419305.42510878,  417756.33163209,  283283.88270308,
        219878.2195848 ,  292304.40347465,  424495.77891535,
        378505.19557349,  311646.9508722 ,  430152.00354456,
        146383.74051994,  113466.96410268,  488980.65554226,
        281371.28830762,  240998.2860961 ,  619958.314167  ,
        215842.6525778 ,  124730.56299435,  393862.32501172,
        105499.27431098,  217414.56255368,  155088.19181371,
        282172.79248834,  105499.27431098,  596847.57415278,
          3378.01724926,  651623.00213371,  426358.0747032 ,
        270532.42026512,  449564.38743223,  312204.88429698,
        407435.68601503,  165677.40500487,  497039.32168543,
         99768.15775511,  285809.3162705 ,  254185.23648831,
        352923.7436867 ,  216698.71771879,  289502.26306286,
        193079.92261425,  466598.31962507,  296603.54943185,
        277080.62523668,  241423.94142947, 1616732.59823094,
        -46911.69510309,  146645.26170966,  329020.95060802,
        375430.32708864,  329020.95060802,  123946.18191165,
        730424.07795943, 1055470.52752014,  179020.76281993,
        103781.98208287,  265416.8691287 ,   31150.23223232,
        326204.07656768,  182513.86231512,  332896.77394668,
        180495.35399261,  186478.90480285,  188813.35278976,
        451641.44814319,  292802.07184   ,  374124.7134463 ,
        466813.5878231 ])

In [39]:
r2_score(y_test, y_preds)

0.630948275545617

In [41]:
## running the above processes several times for a large dataset
scores=[]
for i in range(1000):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_preds=pipe.predict(x_test)
    scores.append(r2_score(y_test,y_preds))

In [42]:
scores

[0.6590970513927552,
 0.47859272055064983,
 0.6204540606089384,
 0.5369852689622819,
 0.8188949573589013,
 0.6836043556193605,
 0.6276695816668298,
 0.6298680300907258,
 0.6720654400632957,
 0.5700627243092438,
 0.6516385880842521,
 0.6085818358493164,
 0.457136918868859,
 0.6672862283618534,
 0.664966653900981,
 0.6278575539053151,
 0.4880869749370509,
 0.6657793574976818,
 0.6089189274059401,
 0.6361211679943964,
 0.6410135664370675,
 0.621071377384018,
 0.7365263253865879,
 0.6403753842494883,
 0.549209560100828,
 0.49867240328152207,
 0.6732789866411406,
 0.7035527164508188,
 0.7253948405830071,
 0.6009310809310515,
 0.624518819906333,
 0.6468948879113373,
 0.7724252837003481,
 0.7854215568017935,
 0.562239420846312,
 0.6851655414023812,
 0.5813521052335726,
 0.6169437004952315,
 0.5392452047504492,
 0.7164198710101277,
 0.33331574572725786,
 0.6733692575279024,
 0.573163946242421,
 0.6792737264345676,
 0.6836794336954204,
 0.6975092160115262,
 0.5258676247171497,
 0.5882263262475144,
 0.7540168288005004,
 0.6861744090087054,
 0.5038062781881746,
 0.5909312807808577,
 0.6325604244284253,
 0.6638858273401873,
 0.5765279879736457,
 0.6974809928465827,
 0.7171752118302054,
 0.7195077096412229,
 0.7619092882102596,
 0.4842846973245254,
 0.5849536511545839,
 0.5244368044389188,
 0.43303689447997706,
 0.6189287407895745,
 0.607534525087815,
 0.6417276244115995,
 0.4810239296322877,
 0.6591165165902115,
 0.6214415640375663,
 0.7466743442387105,
 0.6997152441813015,
 0.758568605409484,
 0.5796143213941884,
 0.6844326482666663,
 0.5518011038353324,
 0.5707572877864114,
 0.44928738969404347,
 0.6102704426933832,
 0.5737920016887492,
 0.6460953177466738,
 0.565827271694899,
 0.6093263398440866,
 0.6759133729164393,
 0.7370409679228261,
 0.6886973699736811,
 0.6360701117726506,
 0.6852012644174021,
 0.5372644598962153,
 0.6029507528036824,
 0.6384104767109944,
 0.6810939914461658,
 0.6238325627380483,
 0.6883288815233011,
 0.4944771332970669,
 0.6330469712363012,
 0.6590359073679228,
 0.636519072201641,
 0.6856527368798939,
 0.6751750766612354,
 0.6002532334366271,
 0.689900052272935,
 0.6600018689506751,
 0.6837527416836234,
 0.5929975993165127,
 0.7041366722042308,
 0.5711935631792617,
 0.6078451853045572,
 0.5764326972100775,
 0.5850425347677009,
 0.7335661495000689,
 0.6788865676722684,
 0.6641449740163925,
 0.4864459595530115,
 0.6955977666119908,
 0.7001149235535461,
 0.5636574470503988,
 0.590222805783879,
 0.6525671069141656,
 0.5094953158831038,
 0.7228260493419041,
 0.6581409889427061,
 0.5953067053677326,
 0.7075028810002657,
 0.6261052135194556,
 0.821649210118576,
 0.6810054395428757,
 0.6376566764311711,
 0.6239454117579943,
 0.5206638612069041,
 0.550394269727783,
 0.6062873318040539,
 0.5323455473795895,
 0.6578489771532954,
 0.6243116658379833,
 0.7695910851510771,
 0.7148942570344503,
 0.5440270858350081,
 0.7128578148482756,
 0.664442503116639,
 0.559159635111206,
 0.7181102785681601,
 0.5867065356703993,
 0.6612103158521527,
 0.7152533938870096,
 0.6281531337077524,
 0.5546165120836384,
 0.6359515683281994,
 0.5880676427470597,
 0.5634807415690722,
 0.6364460198505723,
 0.6277566913898824,
 0.7724245156372361,
 0.5657193225306933,
 0.5011958445790194,
 0.6341009250111733,
 0.6587698118558681,
 0.4217265345347754,
 0.7311898542911864,
 0.6413535912939343,
 0.6780718379706384,
 0.6476167011992635,
 0.5930634844811011,
 0.6642524489991453,
 0.570621961953332,
 0.581204380661174,
 0.6902740128322113,
 0.6608555392134507,
 0.49812578781646866,
 0.5687689366380785,
 0.6962844313224633,
 0.6918209882967874,
 0.6497453246712436,
 0.8248899031414723,
 0.7189923442264898,
 0.5407678366360791,
 0.6143146233499353,
 0.6632340597953923,
 0.6112923064712503,
 0.7143377069944086,
 0.6795716837164995,
 0.6414275357233137,
 0.6170024140739647,
 0.6724382974141552,
 0.6389818871657449,
 0.504939504774431,
 0.6668425889937277,
 0.7358474677555404,
 0.7043946613421783,
 0.6905561887879117,
 0.5693943501254033,
 0.711174073954209,
 0.6618306035355912,
 0.5790648566912311,
 0.7203235895232146,
 0.7293088588383734,
 0.6272113074305343,
 0.6318212066983147,
 0.7493935398337248,
 0.40232342096447793,
 0.7296912534060671,
 0.7157308999460873,
 0.4747032885377537,
 0.623540876650706,
 0.7847430181635238,
 0.5828661988129404,
 0.6723296167435168,
 0.771129789625981,
 0.5840131501392469,
 0.6766853908492704,
 0.30088399321380377,
 0.4906245002143048,
 0.4982992311517257,
 0.5691092220448488,
 0.6186197369565408,
 0.6759754194250267,
 0.6179295530218003,
 0.5303817635520771,
 0.6194128561739003,
 0.5417920498490167,
 0.5760313839433615,
 0.5905194340203579,
 0.6819056619468136,
 0.47552629521933487,
 0.4958604326991395,
 0.5583627314114697,
 0.7244242448032228,
 0.7406412668031384,
 0.6437536109377353,
 0.7309061884775652,
 0.5834361194363066,
 0.5508759432122887,
 0.590817762279147,
 0.6307909151288256,
 0.44071245046299967,
 0.7245029670680593,
 0.5867084819905546,
 0.7054052234200541,
 0.6089865652249435,
 0.5297501991254605,
 0.5939908296106022,
 0.570561030228834,
 0.48454343613792916,
 0.5201497228252538,
 0.6399705729901259,
 0.4824172759333669,
 0.7213437295112868,
 0.7796701085378928,
 0.7463186910065648,
 0.7799341925149837,
 0.5432713558098459,
 0.6070974092977577,
 0.5083749087922012,
 0.5594163179952689,
 0.651029957394634,
 0.5879748352229305,
 0.7699468490169923,
 0.5591523184150347,
 0.6989211392098433,
 0.6560738179866137,
 0.564478133823787,
 0.715424399448279,
 0.7589251031922141,
 0.7047998833731244,
 0.7751377618240771,
 0.6347444664039438,
 0.5780293956732987,
 0.6548709529669128,
 0.6529985417090991,
 0.4747798689239928,
 0.5339227856578127,
 0.6272489602034537,
 0.5494359195945484,
 0.6221175533623241,
 0.6177823006317524,
 0.6958535267247541,
 0.6150408678797744,
 0.7534739993621729,
 0.6969518967820107,
 0.6287165203753481,
 0.7884405943565318,
 0.6615571098896458,
 0.6544856527478422,
 0.6888745093963724,
 0.7344420588713229,
 0.7173681334909139,
 0.5663909368922999,
 0.7224464944753433,
 0.5928087331244156,
 0.45379543260355215,
 0.45184436769285674,
 0.5196523659761758,
 0.691287807041481,
 0.5406765481629463,
 0.750888221546532,
 0.8132138946084193,
 0.63095520821809,
 0.7431844397164846,
 0.7010512161679929,
 0.5330990910938314,
 0.6901716505747688,
 0.7690701839404315,
 0.7418418334791808,
 0.7634509332895489,
 0.4872286986343831,
 0.6371389561624741,
 0.5925553003098645,
 0.7820633827411542,
 0.6918050112552807,
 0.6490681247001103,
 0.6969565007317262,
 0.674868491337323,
 0.6013867089680998,
 0.511634499410186,
 0.49945390351690966,
 0.5581293905602862,
 0.7374875312054909,
 0.5830899134305503,
 0.6254073047129186,
 0.6566240395950047,
 0.5117569406966178,
 0.47566133571568614,
 0.5931507171662666,
 0.5330886562684845,
 0.5698101793689379,
 0.6196784507050551,
 0.5462540433794841,
 0.6354350485752392,
 0.7232973498392307,
 0.6937588529494063,
 0.5143315817346199,
 0.6528967556633396,
 0.5088601385054319,
 0.5934340776107501,
 0.5731365571988123,
 0.6980062893232102,
 0.6015708344549462,
 0.5097761806846247,
 0.6708960660454073,
 0.6187333484530928,
 0.5727990640711849,
 0.7390127285056858,
 0.7318992371018758,
 0.5999528309922101,
 0.671412912046771,
 0.6914508441014908,
 0.644872062627557,
 0.6674186010178442,
 0.5894667859422718,
 0.6959528326842693,
 0.6132575125888109,
 0.743598482402576,
 0.7074346630324695,
 0.5742503619801238,
 0.46032729920689097,
 0.7286076956722161,
 0.6677519081567729,
 0.6984707488802079,
 0.6427848030876764,
 0.7188332091709833,
 0.5833636599994213,
 0.7067922698010359,
 0.6772217770370355,
 0.5386124724811845,
 0.6918151612135839,
 0.7148767097088156,
 0.5634538582107373,
 0.6776458180113458,
 0.4644918360996605,
 0.7160573454106449,
 0.7338735640956425,
 0.6808298567459355,
 0.6248942254935212,
 0.6434582114512375,
 0.6781468107370908,
 0.5148524620754521,
 0.5618046173339319,
 0.6845735456987001,
 0.6169227112244813,
 0.7351778568912186,
 0.7702522932808414,
 0.6134325917490602,
 0.6988812706960845,
 0.7054221953846178,
 0.7891579919471603,
 0.6887812671876707,
 0.7047063764889262,
 0.6861301543865728,
 0.6378403174176206,
 0.5647600239909175,
 0.41558787361461624,
 0.734441327486683,
 0.5622263088284277,
 0.8082372738720801,
 0.37853088049255224,
 0.6542589096444309,
 0.7097736801312065,
 0.5557324762007785,
 0.5941393235251551,
 0.7002759458237431,
 0.7136378322576797,
 0.6291578861193325,
 0.5690813760804335,
 0.558784662399721,
 0.4976674434880737,
 0.5772627347243364,
 0.5775846974496284,
 0.5745960594735184,
 0.6245025292875375,
 0.7037860503246839,
 0.6685630445857764,
 0.686143367421646,
 0.6551330843007988,
 0.6450606215398056,
 0.5172826772881368,
 0.5839865736005103,
 0.5474580706638794,
 0.47027483149520977,
 0.692824573206164,
 0.6768339801738381,
 0.6701947100324437,
 0.7379810260757806,
 0.6722581347337294,
 0.6886490398830727,
 0.6500380002821855,
 0.6334023707103094,
 0.5793633367541865,
 0.43451829707918477,
 0.7381330809074447,
 0.5300786791737524,
 0.6585637114954365,
 0.681578350408681,
 0.7746431520825334,
 0.6276004127058863,
 0.8457042416667213,
 0.6071594299298039,
 0.7763125623338653,
 0.5834912175644379,
 0.7060888872509674,
 0.6469656351794136,
 0.7131698946234873,
 0.6412637958061134,
 0.6707731091751252,
 0.5887473933094327,
 0.8022386218034767,
 0.772059183083609,
 0.7426674753140314,
 0.7215514904744719,
 0.624184595288924,
 0.5660574150181121,
 0.7467806229094635,
 0.7764815156916202,
 0.54972233416299,
 0.5774634633024351,
 0.6332966125688329,
 0.6491050979386206,
 0.640378453675035,
 0.49613376972308665,
 0.5133322270518854,
 0.7295561575890777,
 0.6464851859294808,
 0.7460907426319466,
 0.5490160739914127,
 0.589165703202877,
 0.7733060366200518,
 0.5099630965032285,
 0.622230438177098,
 0.6778861147339867,
 0.598902063678366,
 0.6884029062759731,
 0.6949618169908309,
 0.49056460009522906,
 0.5428728300825922,
 0.3508126815893978,
 0.6840102187818846,
 0.7005615473230673,
 0.7561296289724144,
 0.6048487234492019,
 0.6267161622926505,
 0.7329139668559987,
 0.5341960685611522,
 0.5449833522320717,
 0.6002475838615964,
 0.6092399515452376,
 0.5348785497151947,
 0.5553506628211067,
 0.5177813599914578,
 0.6340229265219406,
 0.580569434104838,
 0.7406130654389788,
 0.6327751003749278,
 0.5025794088837057,
 0.7762661205676371,
 0.5811849499314159,
 0.6247563382358012,
 0.6711217927088917,
 0.5491760254209528,
 0.7010630417931801,
 0.6499011592389492,
 0.621144034070983,
 0.7796044759642389,
 0.6826666310796008,
 0.599966244945198,
 0.5605431747266145,
 0.6312069637221065,
 0.5008345066664294,
 0.6723137231541787,
 0.6658503663227989,
 0.7637732952503052,
 0.6872072142429162,
 0.6535026306473226,
 0.642481838122414,
 0.6291948557021536,
 0.6376748616419048,
 0.725658346531273,
 0.660369983195033,
 0.7835623170445373,
 0.7193179852967511,
 0.7590913723971981,
 0.5945887094936803,
 0.6750782166695455,
 0.6941672625393058,
 0.6832380440096875,
 0.4978065377240046,
 0.5697457005917441,
 0.5324609761539525,
 0.4731197144057526,
 0.635217540494183,
 0.6889776197018176,
 0.7635452172372585,
 0.6536081115194197,
 0.6277302115027374,
 0.6291974456940381,
 0.6367630524290615,
 0.7376547986979882,
 0.5087935452803634,
 0.5793757261926096,
 0.6378522153186107,
 0.5298876983951171,
 0.6777570386410483,
 0.575848146468295,
 0.6923995233259915,
 0.6007411289929618,
 0.6790203751174368,
 0.5969978446329531,
 0.6958905945015755,
 0.463335553846854,
 0.725611607465046,
 0.3236591594342373,
 0.7312969911707572,
 0.5020843765430405,
 0.6214163090271736,
 0.673939274480521,
 0.5376591137844259,
 0.7244988652671434,
 0.6303978592256447,
 0.7147584508910736,
 0.5554032652146947,
 0.514393189322292,
 0.6955387047091008,
 0.7086524774292298,
 0.6141772649885588,
 0.4917842217679883,
 0.7054068394356141,
 0.5894014329870094,
 0.6580594381152531,
 0.6745312486408298,
 0.8043975560601916,
 0.6601707103728791,
 0.7386525191300064,
 0.6318357152550649,
 0.6403528030978021,
 0.6471889578289435,
 0.675350335286784,
 0.6243823667698462,
 0.5746419865508394,
 0.6940029104778772,
 0.6786338864452484,
 0.76107992842415,
 0.6666626716320547,
 0.6318191702317443,
 0.5933418076103998,
 0.646089193563254,
 0.49720013212349956,
 0.607437354897024,
 0.5410100487938727,
 0.5789562984511503,
 0.6937888654313847,
 0.6329738068990556,
 0.7000584199659625,
 0.6931657122130515,
 0.5898644937993032,
 0.697192337174372,
 0.7193233727705459,
 0.7177848448751278,
 0.6054034071861762,
 0.3914992057964014,
 0.5581130916570395,
 0.5620093086878156,
 0.5643360076478843,
 0.49283210902847996,
 0.5107669924203583,
 0.5706202263327576,
 0.7111545623215858,
 0.6007771088496331,
 0.5168510319370553,
 0.7530019153300127,
 0.4860299548542434,
 0.6078051569304569,
 0.6830744144704824,
 0.5960728273221448,
 0.5023144886531146,
 0.5915280453267616,
 0.6128203819177975,
 0.6011553956600172,
 0.6678921255200316,
 0.5918379333153168,
 0.37127251957496743,
 0.5820841738545055,
 0.6802619055335053,
 0.6069391244971198,
 0.5097681049625813,
 0.7211505009487413,
 0.6030110031594996,
 0.5126748054908431,
 0.7560792421821378,
 0.5958674030219004,
 0.693524717574318,
 0.5129719679163816,
 0.671662572934615,
 0.6444083982205295,
 0.5865259622895441,
 0.7234681761673475,
 0.700789088679716,
 0.643283816047931,
 0.5160260620487171,
 0.5842417586794216,
 0.6789402619511703,
 0.6658630299925279,
 0.7609569440370013,
 0.5432449468941114,
 0.5651150304883054,
 0.6711263509228587,
 0.6752571644315197,
 0.6024263966344594,
 0.4849434152255975,
 0.6955648594344483,
 0.5975628944882299,
 0.43525734721327713,
 0.6040011999070286,
 0.6484634617485878,
 0.6737706909415804,
 0.6190177852053038,
 0.7503736583410024,
 0.7700413145886557,
 0.6501920797027056,
 0.6499166396008003,
 0.5853841032135201,
 0.4607462148285859,
 0.6752838220135002,
 0.664724146230399,
 0.7255944446962768,
 0.7687593840937067,
 0.5620407173054665,
 0.5158123211314755,
 0.479799978367105,
 0.6709683172908445,
 0.6207405147369354,
 0.6989197806653898,
 0.7160620079812834,
 0.7371475076234506,
 0.7503784661026365,
 0.5281087836811258,
 0.6650594810263641,
 0.7352762645037789,
 0.664632352950276,
 0.628599438593682,
 0.658750084159998,
 0.5646923780442158,
 0.7069325665864452,
 0.6584824840521495,
 0.6184988735363947,
 0.5431633270427969,
 0.7207670773717652,
 0.6986028396182968,
 0.5896982752644,
 0.6220449516096318,
 0.8314143615639149,
 0.6329386043047649,
 0.5682060358465241,
 0.7932310422944464,
 0.6064899110943096,
 0.6814859767833745,
 0.6535041464451068,
 0.6541288844640345,
 0.6933890289928587,
 0.711534167927448,
 0.6608406681788364,
 0.5533645424841993,
 0.7516076744903611,
 0.6662990025907778,
 0.47697052722945477,
 0.7039495616936594,
 0.5923811123098408,
 0.7711850505706963,
 0.535379665250796,
 0.6827071861243125,
 0.7223051826028738,
 0.6604420216830862,
 0.6674259483802103,
 0.5333287814911902,
 0.6449010280710183,
 0.675595320027194,
 0.8112922208182705,
 0.7268057919402813,
 0.6569074989086102,
 0.677858347118355,
 0.720629213971593,
 0.7319374851084153,
 0.3422773729981641,
 0.64593663101955,
 0.5556936869952196,
 0.5874200227561961,
 0.6768887555880909,
 0.6747428193383662,
 0.6445281975234285,
 0.621974733404087,
 0.6519493793502578,
 0.6891862852846442,
 0.5977223997295629,
 0.5800399419850418,
 0.7342388168474427,
 0.5286001395929683,
 0.7939854773879416,
 0.6719912234398249,
 0.5888986770984963,
 0.5465815444754674,
 0.6100690012399805,
 0.5038430597851642,
 0.7120786681996657,
 0.5987854922031488,
 0.6298887919016949,
 0.6262325530007595,
 0.7511950317035228,
 0.7566603994357598,
 0.5491414957897592,
 0.6130966082801732,
 0.6367595231958936,
 0.5529790346331309,
 0.592575057864392,
 0.5104407516413791,
 0.5468104159682373,
 0.7319404072041833,
 0.7407233548285888,
 0.6888800792234572,
 0.7489288053515142,
 0.636448412062398,
 0.6011959842150568,
 0.7491267462336426,
 0.6207523779222387,
 0.63321808310812,
 0.6523300664666802,
 0.6658003336716636,
 0.7119915854260312,
 0.6423419274456099,
 0.6178775773701948,
 0.6603845838303639,
 0.6258492533475988,
 0.6268900711422065,
 0.534351333946479,
 0.7578428105072001,
 0.6706461488923394,
 0.6976895098395585,
 0.7044000540012345,
 0.6081140538107188,
 0.5575243099526903,
 0.585092338599654,
 0.5555064868733852,
 0.3625803099553392,
 0.7044971727563023,
 0.670298615166375,
 0.6546570660709405,
 0.805129194273702,
 0.7098553782835257,
 0.7833714688637822,
 0.6411237400992881,
 0.6341781079883486,
 0.637530855459244,
 0.660727805668718,
 0.7001467000944022,
 0.44992349397789,
 0.719013046676542,
 0.7028295254978754,
 0.7349852473538501,
 0.70687028551456,
 0.6578212127343924,
 0.5603505919344813,
 0.7151106742094016,
 0.606623399024122,
 0.6342989331962572,
 0.7559650332836447,
 0.6406348959553323,
 0.5119010932096246,
 0.6221557246746761,
 0.6533155016916112,
 0.5374623501764861,
 0.5977156007769597,
 0.6454570059982456,
 0.7460020862345189,
 0.38882146355460545,
 0.5655310049116876,
 0.5549835681809367,
 0.6417562789660707,
 0.6611969304378471,
 0.5258828364358195,
 0.7881362299291383,
 0.627755282648593,
 0.5990375183358418,
 0.7028622023209898,
 0.6568926671545607,
 0.6553460916032614,
 0.5586779531166275,
 0.7773139826253354,
 0.6599067828507323,
 0.5951028499176375,
 0.4478602848989709,
 0.7270215228162802,
 0.6643170921014915,
 0.7601341950688945,
 0.6538296687227783,
 0.6380248038743981,
 0.4768731185776117,
 0.7088478643892591,
 0.7952401460724743,
 0.5773960928660526,
 0.7391084764668986,
 0.6402601025074534,
 0.5890943417403836,
 0.6388380685579305,
 0.620868572655976,
 0.5657935214955284,
 0.72932941245119,
 0.7584002569467102,
 0.7251365007258382,
 0.708095121796562,
 0.6551142816480371,
 0.49460397893813246,
 0.6089699654897032,
 0.6132970866024712,
 0.5751338939540402,
 0.6889134084750896,
 0.7279070135048182,
 0.6005129073645592,
 0.6351378275769674,
 0.6577504372965064,
 0.5506675239636997,
 0.6092403256965584,
 0.5421163057349387,
 0.5023466860896657,
 0.7453749187393885,
 0.5259099133859436,
 0.7578077863879923,
 0.5563819556537697,
 0.6715044704898854,
 0.5783404246080986,
 0.6568831730965639,
 0.5594340569986866,
 0.6255137091768664,
 0.6024581480839073,
 0.5499572407200233,
 0.6331960851167319,
 0.5749278118664649,
 0.46915134465721786,
 0.6977671096892979,
 0.6209467864463638,
 0.6865485259240277,
 0.7014174393332961,
 0.6599067879588679,
 0.5438074760914635,
 0.6271726286181765,
 0.7163206297081406,
 0.6831458327267018,
 0.6957779726926481,
 0.6545546409487755,
 0.7068480123777574,
 0.7201421708179772,
 0.6279531274190165,
 0.5393262149707425,
 0.7145682898976988,
 0.5720196298543425,
 0.5890454046063469,
 0.6714823904884077,
 0.5258301717286786,
 0.6716074208069015,
 0.6455002325125536,
 0.5129496070399153,
 0.48111084070132215,
 0.6052103859957141,
 0.6927173316177045,
 0.7568654957865584,
 0.5978844048019378,
 0.6837516043188976,
 0.6282609650413583,
 0.5600723515667315,
 0.778842147166199,
 0.7050246257449206,
 0.5950595116255513,
 0.7854625138771448,
 0.6507789571056781,
 0.6795979431079968,
 0.689615148654165,
 0.7229818926978699,
 0.6962144308674162,
 0.5240205480353397,
 0.5729797501541096,
 0.6665773920475258,
 0.6881083721448034,
 0.49773969470177937,
 0.5033116533333956,
 0.7262160350450372,
 0.4668295433335813,
 0.5237128412941386,
 0.6597609423159339,
 0.7814608925162292,
 0.6534508292309527,
 0.5812774652367787,
 0.5697328603599785,
 0.7740518078286382,
 0.6176155933889255,
 0.6737352951505297,
 0.7423961156287626,
 0.5260154699993492,
 0.702629722361263,
 0.4956715332927444,
 0.6944245776014835,
 0.6326694880287671,
 0.5527433119784664,
 0.6196197166980342,
 0.5517348440036188,
 0.7529891220844878,
 0.511837961812601,
 0.565269060699761,
 0.5605502224650699,
 0.6918913350809524,
 0.6340927505430378,
 0.6702976219330589,
 0.7404926443433137,
 0.5021794781412109,
 0.5741827506065538,
 0.6728611136039915,
 0.7188967129339727,
 0.4986846874188827,
 0.6103414183868137,
 0.7186837425301331,
 0.6509168450055013,
 0.6502765184349745,
 0.6382765913949038,

In [44]:
np.argmax(scores)

433

In [45]:
scores[np.argmax(scores)]

0.8457042416667213

In [47]:
## Now training the model at the random state that gives the maximum r2_score
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(x_train,y_train)
y_preds=pipe.predict(x_test)
r2_score(y_test,y_preds)

0.8457042416667213

In [49]:
## Now dumping(saving) the pipeline using pickle
import pickle
pickle.dump(pipe,open('Linearregression.pkl','wb'))

In [50]:
## Predicting a specific column/row
pipe.predict(pd.DataFrame([['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']],columns=['name','company','year','kms_driven','fuel_type']))

array([458900.81022717])